### ISSUE TITLE
About the submission reults of semantic segmentation task 

### ISSUE THREAD

**Issue by WhateverChan** [sharibox/EndoCV2020#1]
I am a little unsure about what file format should I submit finally.
With my comprehension, I should submit a zip file containing tif-format results of all test data. But the linked example you gave with the semantic segmentation task shows a jpg file generated from a tif result for a test sample. 
Also, should I add a 'blood' class prediction to the result? Or just 5 classes.

**Comment by sharib-vision** [comment]
Hi, The submission file format should be '.tif' (5 channels). 

We have removed the blood class for this year as we have less samples for this class. That means it's just 5 class. 

Please let us know if you have more questions. You can send us the submissions to review in case it fails! Happy to help.

**Comment by WhateverChan** [comment]
> Hi, The submission file format should be '.tif' (5 channels).
> 
> We have removed the blood class for this year as we have less samples for this class. That means it's just 5 class.
> 
> Please let us know if you have more questions. You can send us the submissions to review in case it fails! Happy to help.

OK. Thank you for the reply!
